### ISSUE TITLE
wrapper has no run_redlines method

### ISSUE THREAD

**Issue by regstuff** [JSv4/Python-Redlines#2]
Kudos on a great project. This is one thing I've sorely missed in python - the ability to create track changed word docs.
However, using the python wrapper like so:
`
output = wrapper.run_redlines('AuthorTag', '/path/to/original.docx', '/path/to/modified.docx')
`
throws an error saying wrapper has no run_redlines method.

Running the redlines.exe in the bin folder using subprocess works just fine, so right now I'm utilizing that, but would be nice to use the python wrapper.

**Comment by JSv4** [comment]
Thanks @regstuff. I'll try to take a look this week.

**Comment by JSv4** [comment]
Oh, also, do you mind sharing the details of your system env?

**Comment by rishabh-sagar-20** [comment]
Is that a typo in the documentation? Since I can see a method in the package with the name `run_redline`

**Comment by JSv4** [comment]
Yeah, should just be a typo in the markdown documentation. Updated the MD docs.
